# Permalinks
#
permalink:           pretty

# Setup
title:               This Guy Right Here
tagline:             'Writes Right Here'
description:         'This guy right here writes right here. About anything he wants. Now go eat some croissants. ğŸ¥ğŸ¥ğŸ¥'
url:                 http://thisguyrighthere.com
baseurl:             'http://thisguyrighthere.com'
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             2.0.0
